import Nav from './(components)/Nav'
import AuthProvider from './(components)/AuthProvider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>
        <Nav />
        <div>{children}</div>
      </body>
      </AuthProvider>
    </html>
  )
}
